# start with a base image
FROM ubuntu:14.04

# install dependencies
RUN apt-get update
RUN apt-get install -y autoconf automake libtool
RUN apt-get install -y libpng12-dev
RUN apt-get install -y libjpeg62-dev
RUN apt-get install -y g++
RUN apt-get install -y libtiff4-dev
RUN apt-get install -y libopencv-dev libtesseract-dev
RUN apt-get install -y git
RUN apt-get install -y cmake
RUN apt-get install -y build-essential
RUN apt-get install -y libleptonica-dev
RUN apt-get install -y liblog4cplus-dev
RUN apt-get install -y libcurl3-dev
RUN apt-get install -y python3
RUN apt-get install -y tk8.5 tcl8.5 tk8.5-dev tcl8.5-dev
RUN apt-get install -y imagemagick
RUN apt-get install -y wget
RUN apt-get install -y python3-pip

# build leptonica
RUN wget http://www.leptonica.org/source/leptonica-1.79.0.tar.gz
RUN tar -zxvf leptonica-1.79.0.tar.gz
WORKDIR leptonica-1.79.0
RUN ./configure
RUN make
RUN make install
RUN ldconfig
WORKDIR /
RUN ls

ADD requirements.txt /
RUN pip3 install -r requirements.txt

# build tesseract
# RUN wget https://github.com/tesseract-ocr/tesseract/archive/4.1.1.tar.gz
# RUN tar -zxvf 4.1.1.tar.gz
# WORKDIR 4.1.1/
# RUN ls
# RUN chmoud u+x autogen.sh & ./autogen.sh
# RUN ./configure
# RUN make
# RUN make install
# RUN ldconfig
RUN apt install tesseract-ocr -y
RUN cd ..

# # download the relevant Tesseract English Language Packages
# RUN wget https://tesseract-ocr.googlecode.com/files/tesseract-ocr-3.02.eng.tar.gz
# RUN tar -xf tesseract-ocr-3.02.eng.tar.gz
# RUN sudo cp -r tesseract-ocr/tessdata /usr/local/share/

# update working directories
ADD ./flask_server /flask_server
WORKDIR /flask_server

EXPOSE 80
CMD ["python3", "app.py"]